name: GUI build

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'osu_stick_gui'

jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: |
         cd osu_stick_gui
         flutter build apk
     - name: Upload Artifact
       uses: actions/upload-artifact@v3.1.2
       with:
         name: osg-apks
         path: 'osu_stick_gui/build/app/outputs/apk/release/*'
