name: DyLib build

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/build-lib.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26
          add-to-path: true
      - name: Install and configure dependencies
        run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
          cargo install cargo-ndk
      - name: Run build
        run: cargo ndk -t armeabi-v7a -t arm64-v8a -t x86_64 -o ./jniLibs build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Cross-Platform Library
          path: |
            ./jniLibs/*
