name: DyLib build

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        sys_v: []
        paths: []

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
    - name: Build
      run: |
        rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android
        cargo build --target aarch64-linux-android --release
        cargo build --target armv7-linux-androideabi --release
        cargo build --target i686-linux-android --release

    - name: Upload Android
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "Lib"
        path: 'target/**'